apiVersion: v1
kind: Service
metadata:
  name: banking-app-service
spec:
  # This creates a public IP address using the Azure Load Balancer
  type: LoadBalancer
  selector:
    # This must match the 'app' label in your deployment
    app: banking-app
  ports:
  - port: 80 # The public port people will access
    targetPort: 8501 # The port your container is running on